"""unique project member

Revision ID: 0171676e9c6d
Revises: 4ca065a16724
Create Date: 2026-08-11 03:42:41.605701
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0171676e9c6d'
down_revision: Union[str, None] = '4ca065a16724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_member_user', 'project_members', ['project_id', 'platform_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_member_user', 'project_members', type_='unique')
    # ### end Alembic commands ###
