"""initial schema

Revision ID: 4ca065a16724
Revises:
Create Date: 2026-08-10 17:16:25.872614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ca065a16724'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_commit', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifacts_status'), 'artifacts', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('evidence_state', sa.String(length=32), nullable=False),
    sa.Column('review_level', sa.String(length=32), nullable=False),
    sa.Column('use_state', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_project_id'), 'claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('context_packages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('context_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('objects_json', sa.JSON(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('excluded_by_budget_json', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_id')
    )
    op.create_index(op.f('ix_context_packages_project_id'), 'context_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_context_packages_status'), 'context_packages', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('why_material', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('recommendation_basis', sa.Text(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=True),
    sa.Column('unresolved_uncertainty', sa.Text(), nullable=True),
    sa.Column('reversibility', sa.Text(), nullable=True),
    sa.Column('blocking_scope_json', sa.JSON(), nullable=True),
    sa.Column('continue_scope_json', sa.JSON(), nullable=True),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('affected_object', sa.String(length=128), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.Column('answered_by', sa.String(length=128), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_revision', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_decision_id'), 'decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_decisions_fingerprint'), 'decisions', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('schema', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('actor_json', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_refs_json', sa.JSON(), nullable=True),
    sa.Column('literature_json', sa.JSON(), nullable=True),
    sa.Column('computational_json', sa.JSON(), nullable=True),
    sa.Column('model_annotation_json', sa.JSON(), nullable=True),
    sa.Column('limitations_json', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_table('executor_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('executor', sa.String(length=64), nullable=False),
    sa.Column('executor_profile', sa.String(length=128), nullable=True),
    sa.Column('resolved_model', sa.String(length=256), nullable=True),
    sa.Column('remote_session_id', sa.String(length=256), nullable=True),
    sa.Column('last_event_sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executor_sessions_project_id'), 'executor_sessions', ['project_id'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('cc_project', sa.String(length=128), nullable=True),
    sa.Column('cc_session_key', sa.String(length=256), nullable=True),
    sa.Column('actor_json', sa.JSON(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_event_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_inbound_messages_message_id'), 'inbound_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_inbound_messages_project_id'), 'inbound_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('investigation_plan', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_leases_project_id'), 'leases', ['project_id'], unique=False)
    op.create_index(op.f('ix_leases_run_id'), 'leases', ['run_id'], unique=False)
    op.create_index(op.f('ix_leases_task_id'), 'leases', ['task_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_destination'), 'outbox', ['destination'], unique=False)
    op.create_index(op.f('ix_outbox_project_id'), 'outbox', ['project_id'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_table('plan_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_index(op.f('ix_plan_revisions_project_id'), 'plan_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_plan_revisions_status'), 'plan_revisions', ['status'], unique=False)
    op.create_table('project_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('binding_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cc_project', sa.String(length=128), nullable=True),
    sa.Column('session_key', sa.String(length=256), nullable=True),
    sa.Column('chat_id', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_id')
    )
    op.create_index(op.f('ix_project_bindings_project_id'), 'project_bindings', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_bindings_status'), 'project_bindings', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('can_approve_decisions', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_status'), 'project_members', ['status'], unique=False)
    op.create_table('projection_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=256), nullable=False),
    sa.Column('section_key', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projection_states_project_id'), 'projection_states', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workspace_root', sa.Text(), nullable=True),
    sa.Column('policy_json', sa.JSON(), nullable=True),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.Column('initial_brief_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_project_id'), 'questions', ['project_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('platform_message_id', sa.String(length=256), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_idempotency_key'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('executor', sa.String(length=64), nullable=True),
    sa.Column('executor_profile', sa.String(length=128), nullable=True),
    sa.Column('resolved_model', sa.String(length=256), nullable=True),
    sa.Column('reasoning_effort', sa.String(length=32), nullable=True),
    sa.Column('configuration_source', sa.String(length=32), nullable=True),
    sa.Column('process_instance_id', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.String(length=256), nullable=True),
    sa.Column('turn_id', sa.String(length=256), nullable=True),
    sa.Column('last_event_sequence', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('lease_token', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_run_id'), 'runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_task_id'), 'runs', ['task_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('contract_json', sa.JSON(), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('blocked_by_json', sa.JSON(), nullable=True),
    sa.Column('depends_on_json', sa.JSON(), nullable=True),
    sa.Column('current_run_id', sa.String(length=64), nullable=True),
    sa.Column('lease_token', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_table('taste_rule_proposals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('proposal_id', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=False),
    sa.Column('inferred_rule', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_taste_rule_proposals_project_id'), 'taste_rule_proposals', ['project_id'], unique=False)
    op.create_index(op.f('ix_taste_rule_proposals_status'), 'taste_rule_proposals', ['status'], unique=False)
    op.create_table('workspace_locks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_locks_project_id'), 'workspace_locks', ['project_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'evidence_id', name='uq_claim_evidence')
    )
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_evidence_id'), 'claim_evidence', ['evidence_id'], unique=False)
    op.create_table('decision_options',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('option_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scientific_consequence', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'option_id', name='uq_decision_option')
    )
    op.create_index(op.f('ix_decision_options_decision_id'), 'decision_options', ['decision_id'], unique=False)
    op.create_table('outbox_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('outbox_id', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['outbox_id'], ['outbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_attempts_outbox_id'), 'outbox_attempts', ['outbox_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on', name='uq_task_dep')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on'), 'task_dependencies', ['depends_on'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_outbox_attempts_outbox_id'), table_name='outbox_attempts')
    op.drop_table('outbox_attempts')
    op.drop_index(op.f('ix_decision_options_decision_id'), table_name='decision_options')
    op.drop_table('decision_options')
    op.drop_index(op.f('ix_claim_evidence_evidence_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_workspace_locks_project_id'), table_name='workspace_locks')
    op.drop_table('workspace_locks')
    op.drop_index(op.f('ix_taste_rule_proposals_status'), table_name='taste_rule_proposals')
    op.drop_index(op.f('ix_taste_rule_proposals_project_id'), table_name='taste_rule_proposals')
    op.drop_table('taste_rule_proposals')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_runs_task_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_project_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_projection_states_project_id'), table_name='projection_states')
    op.drop_table('projection_states')
    op.drop_index(op.f('ix_project_members_status'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_bindings_status'), table_name='project_bindings')
    op.drop_index(op.f('ix_project_bindings_project_id'), table_name='project_bindings')
    op.drop_table('project_bindings')
    op.drop_index(op.f('ix_plan_revisions_status'), table_name='plan_revisions')
    op.drop_index(op.f('ix_plan_revisions_project_id'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_project_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_destination'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_leases_task_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_run_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_project_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_project_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_message_id'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index(op.f('ix_executor_sessions_project_id'), table_name='executor_sessions')
    op.drop_table('executor_sessions')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_fingerprint'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_context_packages_status'), table_name='context_packages')
    op.drop_index(op.f('ix_context_packages_project_id'), table_name='context_packages')
    op.drop_table('context_packages')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_project_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_artifacts_status'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
